# Memory Size of Python List VS Numpy Array

In [11]:
import sys 

listt=range(1500000)
print(sys.getsizeof(10) * len(listt))

42000000


In [12]:
import sys as s
import numpy as np

numpylist = np.arange(1500000)
print(numpylist.size*numpylist.itemsize)

6000000


# Running time of Python List VS Numpy Array

In [22]:
import numpy as np
import time as t

size = 10000000

L1 = range(size)
L2 = range(size)

#Python List
start = t.time()
result = [(x+y) for x, y in zip(L1,L2)]
print("Python List Took: ", (t.time()-start)*1000)


Python List Took:  1605.1990985870361


In [23]:
import numpy as np
import time as t

size = 100000000

#Numpy Array
A1 = np.arange(size)
A2 = np.arange(size)

start = t.time()
result = A1 + A2
print("Numpy array took: ", (t.time()-start)*1000)

Numpy array took:  400.9251594543457


# Python List Operations VS Numpy Array

In [28]:
#Python List

l1=[1,2,3]
l2=[4,5,6]

result = [(x+y) for x,y in zip(l1,l2)]
print (result)

result = [(x-y) for x,y in zip(l1,l2)]
print (result)

result = [(x*y) for x,y in zip(l1,l2)]
print (result)

result = [(x/y) for x,y in zip(l1,l2)]
print (result)

[5, 7, 9]
[-3, -3, -3]
[4, 10, 18]
[0.25, 0.4, 0.5]


In [29]:
#Numpy Array

import numpy as np

a1=np.array([1,2,3])
a2=np.array([4,5,6])

print (a1+a2)
print (a1-a2)
print (a1*a2)
print (a1/a2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


# ndim Property in Numpy

In [39]:
import numpy as np

aa=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(aa)

aa.ndim



[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [38]:
import numpy as np

a=np.array([1,2,3])
print(a)
a.ndim

[1 2 3]


1

# Itemsize Property in Numpy

In [41]:
import numpy as np

aa=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(aa)
print()
print("SIZE IN BYTES: ",aa.itemsize)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

SIZE IN BYTES:  4


# Change Data Type of Numpy Array Elements

In [44]:
import numpy as np

aa=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Current Data Type: ", aa.dtype)
print("SIZE IN BYTES: ",aa.itemsize)
print(aa)
print()
aa=np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=np.float64)
print("DataType in Float Converted: ",aa.dtype )
print("SIZE IN BYTES: ",aa.itemsize)
print(aa)


Current Data Type:  int32
SIZE IN BYTES:  4
[[1 2 3]
 [4 5 6]
 [7 8 9]]

DataType in Float Converted:  float64
SIZE IN BYTES:  8
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# Size Property Numpy Array 

In [45]:
import numpy as np

aa=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Total no of Elements: ", aa.size)

Total no of Elements:  9


# Show Shape (row,coloumn) Numpy Array Elements

In [46]:
import numpy as np

aa=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Order of Matrix(Array): ", aa.shape)

Order of Matrix(Array):  (3, 3)


# Complex no Intialization of Numpy Array Elements

In [47]:
import numpy as np

aa=np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=complex)
print(aa)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]
 [7.+0.j 8.+0.j 9.+0.j]]


# Zeros() function of Numpy Array Elements

In [49]:
import numpy as np
print(np.zeros((3,2))) #np.zeros((rows,coloums))


[[0. 0.]
 [0. 0.]
 [0. 0.]]


# Ones() function of Numpy Array Elements

In [50]:
import numpy as np
print(np.ones((3,2))) #np.zeros((rows,coloums))

[[1. 1.]
 [1. 1.]
 [1. 1.]]


# Arange() function of Numpy Array Elements

In [51]:
import numpy as np
print(np.arange(1,5))

[1 2 3 4]


In [52]:
import numpy as np
print(np.arange(1,10,2))

[1 3 5 7 9]


# linspace() function of Numpy Array Elements

In [53]:
#it creates sequences of evenly spaced numbers structured as a NumPy array. 
import numpy as np

print(np.linspace(1,5,10))

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


# reshape() function of Numpy Array Elements

In [59]:
import numpy as np

aa=np.array([[1,2,3],[4,5,6]])
print("Order of Matrix(Array): ", aa.shape)

print()

print(aa.reshape(3,2))

Order of Matrix(Array):  (2, 3)

[[1 2]
 [3 4]
 [5 6]]


# ravel() function of Numpy Array Elements

In [60]:
#ravel() flaten ur array

import numpy as np

aa=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Current Data Type: ", aa.dtype)
print("SIZE IN BYTES: ",aa.itemsize)
print(aa)

print()

print(aa.ravel())

Current Data Type:  int32
SIZE IN BYTES:  4
[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3 4 5 6 7 8 9]


# Mathematical function of Numpy Array Elements

In [67]:
import numpy as np

aa=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(aa)

print(aa.min())
print()
print(aa.max())
print()
print(aa.sum())
print()
print(aa.sum(axis=0))
print()
print(aa.sum(axis=1))
print()
print(np.sqrt(aa))
print()
bb = np.array([[9,8,7],[6,5,4],[3,2,1]])
print("Dot Product: ",aa.dot(bb))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
1

9

45

[12 15 18]

[ 6 15 24]

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]

Dot Product:  [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


# std() (Standard Deviation) function of Numpy Array Elements

In [66]:
import numpy as np

aa=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.std(aa))

2.581988897471611


# Indexing & Slicing of Numpy Array Elements

In [76]:
#numpy arrays slicing is same as python list slicing

import numpy as n

a=n.array([1,2,3,4,5,6,7])
a[-2:]

array([6, 7])

In [83]:
import numpy as np
aa=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(aa[-2,2])
aa[-1]

aa[-1,0:2]

6


array([7, 8])

# Iteration of Numpy Array Elements

In [117]:
import numpy as np
aa=np.array([[1,2,3],[4,5,6],[7,8,9]])

for row in aa:
    print(row)
print()    
for cell in aa.flat:
    print (cell)

[1 2 3]
[4 5 6]
[7 8 9]

1
2
3
4
5
6
7
8
9


In [124]:
#USING numpy.nditer

for x in np.nditer(aa,order='C'):    #Print from rows order
    print(x)

print()

for x in np.nditer(aa,order='F'):    #Print from Coloumn order
    print(x)
    
print()

for x in np.nditer(aa,order='F',flags=['external_loop']):    #Print from Coloumn order
    print(x)
    
print()

for x in np.nditer(aa,order='F',op_flags=['readwrite']):
    x[...]=x*x
    

1
16
81
256
625
1296
2401
4096
6561

1
256
2401
16
625
4096
81
1296
6561

[   1  256 2401]
[  16  625 4096]
[  81 1296 6561]



In [137]:
a=np.arange(3,15,4).reshape(3,1)


for x,y in np.nditer([a,aa]):
    print(x,y)



3 1
3 256
3 6561
7 65536
7 390625
7 1679616
11 5764801
11 16777216
11 43046721


# Stacking of Numpy Array Elements

In [90]:
import numpy as np
aa=np.array([[1,2,3],[4,5,6],[7,8,9]])
bb=np.array([[7,8,9],[4,5,6],[1,2,3]])

print(np.vstack((aa,bb)))

print()

print(np.hstack((aa,bb)))

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [7 8 9]
 [4 5 6]
 [1 2 3]]

[[1 2 3 7 8 9]
 [4 5 6 4 5 6]
 [7 8 9 1 2 3]]


In [105]:
a=np.arange(30).reshape(3,10)
print(np.hsplit(a,5))
print()
result=np.hsplit(a,5)
result[4]

print()
print(np.vsplit(a,3))
print()
result=np.vsplit(a,3)
result[1]

[array([[ 0,  1],
       [10, 11],
       [20, 21]]), array([[ 2,  3],
       [12, 13],
       [22, 23]]), array([[ 4,  5],
       [14, 15],
       [24, 25]]), array([[ 6,  7],
       [16, 17],
       [26, 27]]), array([[ 8,  9],
       [18, 19],
       [28, 29]])]


[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]), array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]



array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

# Indexing with Boolean arrays of Numpy Array Elements

In [114]:
aa=np.arange(12).reshape(4,3)
print(aa)
print()
b=aa>4
print(b)
print()

print(aa[b])
print()
aa[b]=69
print(aa)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[False False False]
 [False False  True]
 [ True  True  True]
 [ True  True  True]]

[ 5  6  7  8  9 10 11]

[[ 0  1  2]
 [ 3  4 69]
 [69 69 69]
 [69 69 69]]


# The Difference Between Copy and View of Numpy Array Elements

In [138]:
#COPY


import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [139]:
#VIEW

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[42  2  3  4  5]


In [140]:
#Check if Array Owns it's Data

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)


None
[1 2 3 4 5]


# Joining NumPy Arrays

In [141]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [142]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [143]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# NumPy Searching Arrays

In [144]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)


(array([3, 5, 6], dtype=int64),)


In [145]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [146]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [149]:
#Search Sorted

import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

#Search From the Right Side

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

#Multiple Values

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

1
2
[1 2 3]


# NumPy Filter Array

In [150]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)


[41 43]


The example above will return [41, 43], why?

Because the new filter contains only the values where the filter array had the value True, in this case, index 0 and 2.

In [151]:
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [156]:
import numpy as np

arr = np.arange(10)

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[True, False, True, False, True, False, True, False, True, False]
[0 2 4 6 8]


In [157]:
#Creating Filter Directly From Array

import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]
